### ISSUE TITLE
Is this still working with Bootstrap 3 ?

### ISSUE THREAD

**Issue by kressly** [dkharrat/jquery-tokeninput-bootstrap-theme#1]
Hello
I have downloaded the latest version of Jquery TokenInput and the latest version of Bootstrap and i would like to know whether this can still work .

Also, please how to import the file and where to import it ?

**Comment by dkharrat** [comment]
Probably not. It's been developed for Bootstrap 2. A pull request is welcome to update this project to use Bootstrap 3.
